#!/usr/bin/env bash
# Generate ios/BetterStreamflix/Core/Config/GeneratedSecrets.swift
# Priority: $TMDB_API_KEY env → repo-root local.properties → empty placeholder
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/ios/BetterStreamflix/Core/Config/GeneratedSecrets.swift"
mkdir -p "$(dirname "$OUT")"

KEY="${TMDB_API_KEY:-}"
if [[ -z "$KEY" && -f "$ROOT/local.properties" ]]; then
  KEY="$(grep -E '^TMDB_API_KEY=' "$ROOT/local.properties" | head -1 | cut -d= -f2- | tr -d '\r' || true)"
fi

# Escape for Swift string literal
ESCAPED="${KEY//\\/\\\\}"
ESCAPED="${ESCAPED//\"/\\\"}"

cat > "$OUT" <<EOF
// Auto-generated by ios/ci/generate-secrets.sh — do not edit by hand.
enum GeneratedSecrets {
    static let tmdbAPIKey: String = "${ESCAPED}"
}
EOF

if [[ -n "$KEY" ]]; then
  echo "GeneratedSecrets.swift written (TMDB key present, ${#KEY} chars)"
else
  echo "GeneratedSecrets.swift written (TMDB key empty — set TMDB_API_KEY or local.properties)"
fi
